### ISSUE TITLE
(Re)Move tracker static var

### ISSUE THREAD

**Issue by Astach** [schibsted/account-sdk-android#122]
It makes it hard to unit test if the var is created in an "Android object" doing
`BaseLoginActivity.tracker = mock()` will fail with 
`java.lang.NoClassDefFoundError: android/support/v7/app/AppCompatActivity`
What could be done for that case is to move
```
@Nullable
@JvmStatic
var tracker: UiTracking? = null
```
 in `UiTracking`. 
But I'm wondering if that's not gonna make code messy, calling var from everywhere could and often leads to spaghetti code :it:

**Comment by Nexcius** [comment]
Works correctly, closing
