### ISSUE TITLE
Update Identification screen

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-android#123]
Acceptance Criteria
- Copy: [Merchant Name] [is part of/collaborates with] Schibsted. You'll need a Schibsted account to continue. 
- Set [Merchant name] based on the merchant of the client 
- Copy can be [is part of] or [collaborates with] depending on the merchant type. If internal, use the sentence with [is part of]. If it's external, use the sentence with [collaborates with]
- Current text (ie We only use your...), icon and link for Help will be removed.
- This is used on all identification screens (email + password, email passwordless, mobile passwordless)
- Use "part of" text as default

Note: We are also still waiting for the link for "What is Schibsted account?" so do not add this yet. We will bundle all links on a separate ticket.

Design:
https://schibstedglobal.invisionapp.com/share/6EGRPH852T3#/290278402_Mobile_Web_-_Continue_With_Email_-_Empty_Copy
https://app.zeplin.io/project/5ad8456d755b8f2e0da01dcc/screen/5ad84fdc2c6706e1466f1806

**Comment by mela124** [comment]
Joakim said the endpoint should be ready in PRE. Please check with him on how to get the Merchant Name and Type

**Comment by mela124** [comment]
@Astach there's an added line on this copy. I can also add it later but if you can please update the copy (also updated in Zeplin)

> The Standard is part of Schibsted. You’ll need  a Schibsted account to continue. You can use this account across all Schibsted sites.

**Comment by Astach** [comment]
@mela124  I updated the PR with the correct sentence :)

**Comment by Nexcius** [comment]
closed by #142
