### ISSUE TITLE
Fix issue with launch mode

### ISSUE THREAD

**Issue by Astach** [schibsted/account-sdk-android#136]
the launch mode `SingleTask` is defined for UI activities, in order to have only one instance of the activity, that was done to avoid deeplink to reopen an activity.
It appears that on some devices this behaviour doesn't retain the activity state/ create a new instance. Or something similar.

We have to solve that issue and make sure deeplink still works perfectly

**Comment by damianpetla** [comment]
I had that issue in Omni but removing `AccountUiHook` from my custom Application resolved the problem.
