### ISSUE TITLE
Update "Updated Terms" screen

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-android#140]
Design: https://app.zeplin.io/project/5ad8456d755b8f2e0da01dcc/screen/5ad853996e0687200ea8d7c6

Acceptance criteria:
- Replace "SPiD" with "Schibsted account" this applies also for the acceptance of terms for new user
- This screen applies to:
--- existing user and the terms of Schibsted account or Merchant is updated
--- existing user and the terms of Schibsted account or Merchant has never been accepted
- Remove summary of changes link (and screen)

**Comment by Nexcius** [comment]
This is no longer needed, right @mela124 ?

**Comment by mela124** [comment]
@Nexcius it is still needed, just not right now. We are waiting for the PP docs to be updated first.
