### ISSUE TITLE
User.resumeLastSession() does not fail after user.logout() call

### ISSUE THREAD

**Issue by semenoh** [schibsted/account-sdk-android#187]
### Summary
There is no way to get User except perform login or restore session. So I'm trying to get user by restoring last session. But It returns user even after I preform logout.

### Environment
- SDK Version: 0.10.0
- SDK Module: core
- Android Version: P
- Device Info: Google Pixel 2 XL

### Steps to reproduce
1. Perform login
2. Perform logout
3. Perform restoreLastSession

### Actual result
User is passed to onSuccess callback

### Expected result
onError should be triggered

**Comment by damianpetla** [comment]
Perhaps you missed AccountService in your Activity? In that case logout is not persisted. I had exactly this case. After logging out I killed the app, opened again and I was still logged in. After adding AccountService and binding to Activity it worked fine.

**Comment by Astach** [comment]
@semenoh does this comment ☝️ solve your issue?

**Comment by Nexcius** [comment]
Closing for now, please re-open if the suggested solution does not work
