### ISSUE TITLE
Don't hide the continue button when keyboard is up

### ISSUE THREAD

**Issue by Nexcius** [schibsted/account-sdk-android#214]
This makes it impossible to focus the continue button

**Comment by Astach** [comment]
Continue button will be above the keyboard then all UI will be fucked up. Not hiding the button but let the keyboard going over doesn't work either because UI will not be scrollable anymore.

**Comment by Nexcius** [comment]
We need to find a way around this, as the UIs are unusable for sight-impaired people in their current state

**Comment by Nexcius** [comment]
CLosing this, as this will be part of the accessibility work coming up
