### ISSUE TITLE
Wrong copy on Terms of Use (Account Creation)

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-android#280]
### Summary
On account creation, the copy shown in terms of use page is:

> To create your Schibsted account, you need to accept these terms of use. If you don’t accept you will be logged out.

This is wrong since that last sentence should not be shown. That sentence is only shown for acceptance of terms on log in scenario (not for account creation)

### Environment
- SDK Version: 1.0.0.0-rc6
- SDK Module: 
- Android Version: 6.0.1
- Device Info: Samsung Galaxy Note 4

### Details
Stack trace, screenshots or any other relevant information

### Steps to reproduce
Please let us know how to reproduce this issue

**Comment by Astach** [comment]
See #288
