### ISSUE TITLE
Not possible to copy/paste verification code to verification code field

### ISSUE THREAD

**Issue by brittbugge** [schibsted/account-sdk-android#281]
### Summary
I received a verification code through passwordless login. Copied from email, and tried to paste it to flow in app, but not possible to paste it in field for verification code. Had to type it 

### Environment
- SDK Version: Identity Release 0.6.2 (1528890521)
- SDK Module: 
- Android Version: Android 7
- Device Info: Google Pixel (will test on other devices as well)

### Steps to reproduce
Copy verification code from email and paste it in android test app

**Comment by Nexcius** [comment]
This is a known issue and is due to the design. This was highlighted to and signed off by @mela124 during the design phase. @mela124, please confirm

**Comment by Nexcius** [comment]
> Not a blocker for release but a nice thing to fix in the future
Adding to 1.1

**Comment by Astach** [comment]
See #320
