### ISSUE TITLE
Not sent back to app after forgot password flow

### ISSUE THREAD

**Issue by brittbugge** [schibsted/account-sdk-android#282]
### Summary
If I finish the "forgot password" flow, my password is changed, but I'm not sent back to the app nor a valid link.

### Environment
- SDK Version:  Identity Release 0.6.2 (1528890521) 
- SDK Module: 
- Android Version: Android 7
- Device Info: Google pixel,(will test flow on other mobile when available)

### Details
Link I'm sent to that does not work: https://identity-pre.schibsted.com/flow/passwordchanged/c0ddaukag98lq

![img_1250 2](https://user-images.githubusercontent.com/7941373/41593103-3badcb56-73bf-11e8-97ea-3d6402c1f170.JPG)

### Steps to reproduce
Finish forgot password flow. This is after last step when new password is entered.

**Comment by Astach** [comment]
due to spid bug https://jira.schibsted.io/browse/ID-2431

**Comment by Astach** [comment]
@brittbugge it should work again, can you please confirm and close the issue if it's the case?

**Comment by Astach** [comment]
Fixed
