### ISSUE TITLE
User is not logged in after logging in

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-android#283]
### Summary
After logging in w/ remember me = off, it seems like I am not logged in (DemoApp)

### Environment
- SDK Version: 1.0.0-rc6
- SDK Module: 
- Android Version: 6.0.1
- Device Info: Samsung Galaxy Note 4

### Steps to reproduce
1. Enter mela.cortez+jun19@schibsted.com
2. Enter password and untick "Remember me"
3. Login complete
4. I can't go to the User tab and I am seeing "User can’t be resumed - could not find any previous sessions"

See logs

["LogError1.txt".pdf](https://github.com/schibsted/account-sdk-android/files/2115460/LogError1.txt.pdf)

**Comment by mela124** [comment]
@Astach yes, no problem with ticked

**Comment by Astach** [comment]
I'll try to have your samsung device, can't reproduce on S7 ><

**Comment by Nexcius** [comment]
The demo app was not writing its user to a parcel, might solve the issue. This is a demo app issue though
