### ISSUE TITLE
Can't retrieve user profile

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-android#285]
### Summary
I can't access the user profile after logging in from the ClientApp

### Environment
- SDK Version: 1.0.0-rc6
- SDK Module: 
- Android Version: 6.0.1
- Device Info: Galaxy Note4
- Client App Version: 0.6.3 Build 1529410947

### Details
Stack trace, screenshots or any other relevant information

### Steps to reproduce
1. Login using mela.cortez+jun19@schibsted.com
2. Go to User tab
3. Click User Profile
4. It opens a web browser then immediately switches back to the ClientApp and the Identification Screen
5. I tried to login again using mela.cortez+jun19@schibsted.com and after entering password and clicking "COntinue". It's stuck there for a long time.

[LogError2.pdf](https://github.com/schibsted/account-sdk-android/files/2115474/LogError2.pdf)

**Comment by Nexcius** [comment]
This seems to be an implementation issue in the demo app.
