### ISSUE TITLE
Styling of fonts in the UI module

### ISSUE THREAD

**Issue by Nexcius** [schibsted/account-sdk-android#3]
Requested by Jacek at Viktklubb

See https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html#using-support-lib for details

**Comment by Nexcius** [comment]
Is this something we want to do, @mela124 ?

**Comment by mela124** [comment]
I dont think so. We need to provide a more consistent look to better explain that sites are using Schibsted account.

**Comment by Nexcius** [comment]
Based on @mela124 's answer, I'm closing this
