### ISSUE TITLE
Json parsing fails when getting user profile

### ISSUE THREAD

**Issue by Astach** [schibsted/account-sdk-android#30]
A network error occurred: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 1738 path $.data.addresses

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 1738 path $.data.addresses

**Comment by Nexcius** [comment]
Might be better to return a map with the fields for this, depending on how often this changes in SPiD

**Comment by Astach** [comment]
Fixed by https://github.com/schibsted/account-sdk-android/pull/31
