### ISSUE TITLE
Support Google SmartLock for password retrieval

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#33]
Implementatin docs: https://developers.google.com/identity/smartlock-passwords/android/

We have it at VG today so we don't want to regress on this. Could be an optional feature in the SDK. "Worst case" you could just expose the username and password fields in the login/signup form (since they are two forms now you might need to be a bit creative here)

Håvard noted that Note you should be using Android O password hints in relation to this

**Comment by Astach** [comment]
The smartlock feature is already done #12 (but not released yet), a preview will be released soon
see https://github.com/schibsted/account-sdk-android/tree/master/ui#smartlock

**Comment by Nilzor** [comment]
Awesome! Feel free to close this issue then
