### ISSUE TITLE
Keyboard hides "continue" and "log in" button

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#34]
I have to tap the enter button in order to see the "continue" button (see screen 1 and 2). That's one unnecessary click, and one that repeats in the password form. Might sound like a minor thing but it's 2 unnecessary clicks and adds cognitive strain - if you don't know the form you spend some time looking for buttons to understand how to proceed. 

I suggest either to move the button up so that it's never (or more seldom) hidden by the keyboard in portrait mode, and/or make the enter button on the keyboard also proceed to the next screen automatically. 

Might want to consult som UX guys here, but I think there's improvements to be made :-)

Screen 1: 

![image](https://user-images.githubusercontent.com/990654/37511627-d859861c-28ff-11e8-952d-53d5de69b78a.png)

Screen 2: 

![image](https://user-images.githubusercontent.com/990654/37511755-4c462ce2-2900-11e8-900d-7b7d2a4bcc86.png)

**Comment by Astach** [comment]
That's a good catch, this behavior will not exist anymore in the next release, instead the keyboard isn't shown by default, and the keyboard action is to proceed to then next screen 
See https://github.com/schibsted/account-sdk-android/pull/25
