### ISSUE TITLE
Focus on username and password box upon enter

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#353]
The user should not have to tap the username or password field when you enter those two activities initially. They are not focused by default. They should be.

**Comment by Astach** [comment]
Which version of the SDK?

**Comment by Nilzor** [comment]
`1.5.0`

It also applies to the username form so I'll change the title of the request to that. 

Any chance of having this looked at @idanor ? It sounds like something that should be trivial to fix

**Comment by idanor** [comment]
Hi! Could you explain the problem a bit more @Nilzor ? Difficult to grab the essence of your need by what is described in this thread :)

**Comment by Nilzor** [comment]
Sure I'll try.

## Current flow
- User clicks "log in" in our app
- The Schibsted Account login form is displayed
**- User taps the username field**
- User enters name
- User clicks Next 
- The Schibsted Account password form is displayed
**- User taps the password field**
- User enters password
- User clicks Next
- Schibsted Account flow completed

I want the actions in bold not to be neccessary

**Comment by idanor** [comment]
Thanks, Frode! 

From an Identity product point of view, I have no objections to taking away these steps as long as that works technically. I agree that it would create a better user experience.

**Comment by sa-mao** [comment]
Hi,

We actually already have a [PR](https://github.com/schibsted/account-sdk-android/pull/366) for this, but the previous maintainers advised against implementing it in that way because it might cause inconsistent behaviors across devices. But we would love to get your inputs on the PR.

**Comment by Nilzor** [comment]
Cool, didn't know that. I have now commented in that PR

Mvh
Frode Nilsen
Product Manager for Android apps, CNP - Schibsted Media

**Comment by Nilzor** [comment]
Solved in https://github.com/schibsted/account-sdk-android/pull/407
