### ISSUE TITLE
Get profile data during the first login

### ISSUE THREAD

**Issue by schibsted-rafal-adamek** [schibsted/account-sdk-android#36]
Currently after getting the `User` object from a successful login in `PasswordActivity` we need to make another call to get the user data. This means we're in this unconfirmed state between logging in and receiving any useful user data to display. The call itself (to fetch user details) can also fail which means we'll stay with an empty description of the user.

It would be nice if the object retrieved during the login flow contained full `ProfileDetails` that we could update when necessary.

Because here's the current flow:
- user opens up the `PasswordActivity`
- user passes his credentials
- user is *waiting* for logging in
- user returns to the actual app activity where info about him should be displayed but he needs to wait for that (again, with uncertain state)

I believe this flow could be better from the user experience side.

**Comment by aliak00** [comment]
This seems to be a recurring pattern now:
- id sdk logs in
- activity disappears
- client needs to do some stuff that could error
- on successful completion of other stuff, the user is officially logged in according to client

We've discussed solving this generically by providing some kind of hook in to the login process. It seems a bit more complicated on android after talking to @Nexcius, but the general idea is that after the UI gets a User object, we pass that to the client somehow and then client does what it needs and then gives the UI an "ok to dismiss" signal.

This could work for this scenario as well I believe right? Then you can make your profile calls in this "hook"?

**Comment by schibsted-rafal-adamek** [comment]
If by that you mean that we stay on the SPiD UI progress during fetching the profile data, then that would be good.

**Comment by Nexcius** [comment]
I'm currently working on this. Will update you as soon as I have something
