### ISSUE TITLE
Resolving multiple accounts in smart lock fails first time activity is started

### ISSUE THREAD

**Issue by sorbris** [schibsted/account-sdk-android#363]
### Summary
When cold starting the application, the login flow fails to resolve what credentials to use when there are multiple accounts the first try. It appears that smartLockController is null when the observer on smartLockResult is notified. If I exit the login flow and start it again it succeeds the second time.

### Environment
- SDK Version: 1.2.2
- SDK Module: account-sdk-android-ui, account-sdk-android-smartlock
- Android Version: 8
- Device Info: Emulator

### Steps to reproduce
1. Kill the app when logged out
2. Start it again and try to login when at least two smart lock options are available
3. Select one
4. The dialog closes but nothing else happens

**Comment by Nilzor** [comment]
Don't think this is relevant/applicable anymore? SmartLock works well now
