### ISSUE TITLE
Example app crashes because of missing schibsted_account.conf 

### ISSUE THREAD

**Issue by kamilzych** [schibsted/account-sdk-android#364]
### Summary
I tried to build and run the example app from this repository. It crashes immediately because of missing schibsted_account.conf

It would be really helpful for any external contributor to be able to build the app out-of-the-box.

**Comment by Nexcius** [comment]
In that case, we'd need to publish access and secret keys to Github. Is that something we really want to do?

**Comment by kamilzych** [comment]
@Nexcius well, without it, it's a bit hassle to test any changes in the SDK when trying to contribute, don't you think?

**Comment by Nilzor** [comment]
I have to agree with @Nexcius here, one never commits credentials to a public repo. It's a three-line file, easy to add. I'll give you one if you need Kamil
