### ISSUE TITLE
More clearly mark Create new account page

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#365]
We are experiencing users that create accounts, thinking they've logged into an existing one. If you're a bit quick on the keyboard while entering your existing username and misspell it, you might not notice that you're actually on a sign up page. 

A prominent "UNKOWN EMAIL ENTERED" in red text or something would help make it clearer, or any other distinct marking that you're creating a new account. Can any UX people take a second look at this please, as I don't think the current solution is optimal?

Regards, Frode Nilsen, Schibsted

**Comment by idanor** [comment]
UX talks initiated with Jonas Nilsson by Oussama Sarhraoui/Ida Kristine Norddal.

**Comment by idanor** [comment]
UX aligned with Jonas Nilsson. Issue created and to be followed-up in Jira: https://jira.schibsted.io/browse/ID-2729

**Comment by sa-mao** [comment]
closed by #370
