### ISSUE TITLE
Dismissing the SmartLock dialog causes reload of the username Activity

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#405]
To reproduce:
- Open the solution and modify the example app to [ENABLE smart lock](https://github.com/schibsted/account-sdk-android/blob/master/example/src/main/java/com/schibsted/account/example/MainActivity.java#L115)
- Open the app, click login and click _outside_ of the popup dialog from SmartLock
- Notice how the acitvity restarts

**Comment by zamzterz** [comment]
This is intended in the example app implementation; the relevant parts is that 1) the SDK treating the [dismissal of SmartLock as a failure], and 2) the example app [restarting the login with SmartLock disabled](https://github.com/schibsted/account-sdk-android/blob/880de7adf6a0ed0849870f517cdc5ac171af9783/example/src/main/java/com/schibsted/account/example/MainActivity.java#L154).

I agree it's a bit unnecessary to restart the Activity. Maybe we should treat dismissal of the dialog or any other failure related to SmartLock as a failure only if `SmartLockMode.FORCED` is used.

**Comment by Nilzor** [comment]
Sounds like a plan.

Note that it's not only the example app that is affected, but also production apps using the `ui` module

**Comment by zamzterz** [comment]
@Nilzor This has been fixed in #408, if you're able to help out with review/testing it would be great. 🙂
