### ISSUE TITLE
It's not possible to log in after canceling smartlock dialog

### ISSUE THREAD

**Issue by ziem** [schibsted/account-sdk-android#414]
### Summary
It's not possible to log in after canceling smartlock dialog. Progress is spinning forever.

### Environment
- SDK Version: v1.9.0
- SDK Module: v1.9.0 (smartlock + ui)
- Android Version: 9
- Device Info: OnePlus 6T, Pixel 2

### Details
![device-2019-10-16-102934](https://user-images.githubusercontent.com/1929048/66902080-53511600-f000-11e9-9f91-a74b990d1eb6.png)

### Steps to reproduce
- run the sample app with the following code change (set `smartLockMode` to `SmartlockMode.ENABLED`):
```
final Intent intent = AccountUi.getCallingIntent(getApplicationContext(), AccountUi.FlowType.PASSWORD,
        new AccountUi.Params.Builder()
                .teaserText(getString(R.string.example_teaser_text))
                .smartLockMode(SmartlockMode.ENABLED).build());
startActivityForResult(intent, PASSWORD_REQUEST_CODE);
```
- click login button and dismiss smartlock dialog
- type in your email and click next
- progress will start spinning and nothing will happen

Everything works fine when smartlock is disabled.

This is the output of git bisect, hope it helps:

```
5d8668f68c668d07c824815aec6b7802e60d056f is the first bad commit
commit 5d8668f68c668d07c824815aec6b7802e60d056f
Author: Samuel Gulliksson <zamzterz@users.noreply.github.com>
Date:   Wed Sep 4 12:13:48 2019 +0200

    Ignore SmartLock failure (#408)

    * Fix #405: Ignore SmartLock failures if mode isn't FORCED.

    To avoid unnecessarily requiring the login activity to be restarted if
    SmartLock failed or was cancelled.
```

**Comment by zamzterz** [comment]
Thanks for the detailed report! 🙇  The bug has been found and fixed in #415
