### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by ziem** [schibsted/account-sdk-android#470]
Are there any plans to update this library to AndroidX?

`account-sdk-android` is the last library in our project that needs Jetifier:

> Cannot drop Jetifier due to following external dependencies:
> 
> * com.schibsted.account:account-sdk-android-pulse:2.0.0
> 
> * com.schibsted.account:account-sdk-android-ui:1.13.1
> 
> * com.schibsted.account:account-sdk-android-smartlock:1.13.1

Source: https://github.com/plnice/can-i-drop-jetifier

**Comment by zamzterz** [comment]
Unfortunately, it's nothing we currently have planned.
But we'll keep this ticket open as it something we need to look into (PRs are welcome, as usual 🙂 ).
