### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: SmartLockCallback

### ISSUE THREAD

**Issue by ziem** [schibsted/account-sdk-android#56]
Hi,
today I updated SPiD SDK from 0.8.0 to 0.9.0-beta1:
```
compile "com.schibsted.account:account-sdk-android-core:0.9.0-beta1"
compile "com.schibsted.account:account-sdk-android-ui:0.9.0-beta1"
```

Unfortunately, when I open `PasswordActivity` following error is thrown:
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/schibsted/account/smartlock/SmartLockCallback;

Do you have any idea why? Previously everything worked fine. Adding `disableSmartlock()` changes nothing.

**Comment by Nexcius** [comment]
Hi @ziem 

This is being fixed. You can follow the progress here: https://github.com/schibsted/account-sdk-android/pull/55

**Comment by Nexcius** [comment]
Sovlved by #55
