### ISSUE TITLE
Add jacoco test coverage reports once they support Kotlin

### ISSUE THREAD

**Issue by Nexcius** [schibsted/account-sdk-android#8]
See https://github.com/jacoco/jacoco/issues/552 for status

**Comment by CristianGM** [comment]
Well JaCoCo does support Kotlin, even if there are issues.
We are using it on several projects, we are obviously loosing coverage because generated methods, but it's better than nothing.

**Comment by Nexcius** [comment]
This is being discussed here at the moment https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FKT-18383
I'm closing this for now, will revisit at a later stage
